#!/bin/bash

CHANNELS=(
    "5"
    "6"
    "13"
    "16"
    "19"
    "20"
    "21"
    "26"
)

SELECTED_CHANNEL=${CHANNELS[0]}
CHANNEL_STATE=0

print_help() {
    cat <<- EOH
    Usage:
        $0 <[ch/CH]1-8> <on/off/true/false/ON/OFF>
        $0 --help # prints this message and exits
EOH
}

if [[ $# -lt 2 ]]; then
    print_help
    exit
fi

for i in $@; do
    case $i in
        "ch1"|"CH1"|"1")
            echo "Selected channel 1"
            eval SELECTED_CHANNEL=${CHANNELS[0]}
        ;;
        "ch2"|"CH2"|"2")
            echo "Selected channel 2"
            eval SELECTED_CHANNEL=${CHANNELS[1]}
        ;;
        "ch3"|"CH3"|"3")
            echo "Selected channel 3"
            eval SELECTED_CHANNEL=${CHANNELS[2]}
        ;;
        "ch4"|"CH4"|"4")
            echo "Selected channel 4"
            eval SELECTED_CHANNEL=${CHANNELS[3]}
        ;;
        "ch5"|"CH5"|"5")
            echo "Selected channel 5"
            eval SELECTED_CHANNEL=${CHANNELS[4]}
        ;;
        "ch6"|"CH6"|"6")
            echo "Selected channel 6"
            eval SELECTED_CHANNEL=${CHANNELS[5]}
        ;;
        "ch7"|"CH7"|"7")
            echo "Selected channel 7"
            eval SELECTED_CHANNEL=${CHANNELS[6]}
        ;;
        "ch8"|"CH8"|"8")
            echo "Selected channel 8"
            eval SELECTED_CHANNEL=${CHANNELS[7]}
        ;;
        "--help"|"-h")
            print_help $0
            exit
        ;;
        "ON"|"on"|"true")
            echo "Channel state = on"
            eval CHANNEL_STATE=0
        ;;
        "OFF"|"off"|"false")
            echo "Channel state = off"
            eval CHANNEL_STATE=1
        ;;
        *)
            print_help
            exit
        ;;
    esac
done

############################
##  Do actual work here
############################

# Detect if GPIO pin is already exported
if [[ ! -d "/sys/class/gpio/gpio$SELECTED_CHANNEL" ]]; then
    echo "$SELECTED_CHANNEL" > "/sys/class/gpio/export"
#else
    #&2 < echo "Channel $SELECTED_CHANNEL is already exported!"
    #exit
fi

# Now dump value to GPIO
echo "out" > "/sys/class/gpio/gpio$SELECTED_CHANNEL/direction"
echo "$CHANNEL_STATE" > "/sys/class/gpio/gpio$SELECTED_CHANNEL/value"

echo "GPIO pin $SELECTED_CHANNEL set to $CHANNEL_STATE"


